### ISSUE TITLE
pileup column in .xls file when setting --broad

### ISSUE THREAD

**Issue by ChenFengling** [taoliu/MACS#144]
Hi Tao,
 I wonder what is the meaning of pileup column in .xls file(--broad) as there is no summit in broad peak calling.  I want to calculate correlation of peak strength  between a TF  and a histone marker. Is it OK to correlate the pileup column?

**Comment by AmandaKedaigle** [comment]
I would also love to hear the answer to this question. We are getting an error where the pileup column is giving us hug negative numbers when we use the --broad tag.

**Comment by taoliu** [comment]
@ChenFengling  The pileup in 'broad call' is the average pileup over the entire region -- total pileup / length of the peak. It really depends on what you want to do. If you want to correlate TF with histone mark, I would compute the signal of histone mark at a narrow surrounding region at TF binding sites instead of using MACS2 pileup values which will be affected by peak length.  My suggestion is to make the SPMR (signal per million reads) tracks for both your TF and HM, convert the signal tracks to bigwig, manually define the regions you want to check such as a 200bps window centered at TFBS summit, then extract the average pileup in that window using UCSC tool bigWigAverageOverBed. Afterwards, you can try to do correlation.

**Comment by taoliu** [comment]
@AmandaKedaigle Haven't seen negative numbers for pileup before. Could you explain it more in detail? Thanks!

**Comment by ChenFengling** [comment]
@taoliu THX！Your answer helped  a lot!

**Comment by AmandaKedaigle** [comment]
Thank you @taoliu! We ended up upgrading to version 2.1.1 instead of 2.1.0, and that seems to have fixed the problem.

**Comment by mxenoph** [comment]
I have encountered the same issue concerning negative pileup values as @AmandaKedaigle. Using the same command, macs2 version (macs2 2.1.0.20140616) and cluster resources as in the initial run (which gave the negative pileup values), a second run fixed the problem. The peaks called in both runs are the same but the reported pileup and statistics are negative. Could this be an overflow error?

**Comment by taoliu** [comment]
@mxenoph There was overflow issue in some older versions.
