### ISSUE TITLE
Filter on p-value works in opposite way

### ISSUE THREAD

**Issue by dawe** [taoliu/MACS#151]
When using q-value to filter peak detection (default), the lower the value the smaller is the final peak set. When using p-value, instead, the opposite happens: the lower the p-value the larger is the final peak set, suggesting that p-value filter is acting on the left tail of the distribution. The odd behaviour can be easily reproduced using test data shipped with MACS code:

p = 0.05
```
$ macs2 callpeak -t CTCF_ChIP_200K.bed.gz -g hs -n test_p05 -p 0.05
$ wc -l test_p05_peaks.narrowPeak
    61644 test_p05_peaks.narrowPeak
```

p = 0.01
```
$ macs2 callpeak -t CTCF_ChIP_200K.bed.gz -g hs -n test_p01 -p 0.01
$ wc -l test_p01_peaks.narrowPeak
    113888 test_p01_peaks.narrowPeak
```

p = 0.99
```
$ macs2 callpeak -t CTCF_ChIP_200K.bed.gz -g hs -n test_p99 -p 0.99
$ wc -l test_p99_peaks.narrowPeak
    23 test_p99_peaks.narrowPeak
```

default (q = 0.05)
```
$ macs2 callpeak -t CTCF_ChIP_200K.bed.gz -g hs -n test
$ wc -l test_peaks.narrowPeak
    5985 test_peaks.narrowPeak
```

q = 0.01
```
$ macs2 callpeak -t CTCF_ChIP_200K.bed.gz -g hs -n test -q 0.01
$ wc -l test_peaks.narrowPeak
    2435 test_peaks.narrowPeak
```

**Comment by taoliu** [comment]
Hi Dave, haven't seen your post for a quite long time!!

I think you don't know there is an option in MACS2 to give you a cutoff value analysis report in the current version. If you run macs2 callpeak --cutoff-analysis -t CTCF_ChIP_200K.bed.gz -g hs -n test_p, and you will see a file named 'test_p_cutoff_analysis.txt'. And here is the report, and I will explore it:

``` 
pscore	qscore	npeaks	lpeaks	avelpeak
9.90	5.62	24	7248	302.00
9.60	5.40	24	7521	313.00
9.30	5.20	27	8321	308.00
9.00	4.94	41	12207	297.00
8.70	4.72	46	13612	295.00
8.40	4.49	60	17601	293.00
8.10	4.29	108	30267	280.00
7.80	4.04	117	33418	285.00
7.50	3.81	162	45538	281.00
7.20	3.57	236	65038	275.00
6.90	3.38	303	84322	278.00
6.60	3.11	433	118850	274.00
6.30	2.89	612	166679	272.00
6.00	2.66	819	227947	278.00
5.70	2.45	1217	332670	273.00
5.40	2.18	1830	501677	274.00
5.10	1.97	2435	684317	281.00
4.80	1.73	3494	965949	276.00
4.50	1.56	5015	1394856	278.00
4.20	1.29	6441	1865556	289.00
3.90	1.07	8782	2506733	285.00
3.60	0.83	11982	3460290	288.00
3.30	0.74	67161	17667970	263.00
3.00	0.74	68539	18342382	267.00
2.70	0.64	94372	25616824	271.00
2.40	0.39	105045	29149367	277.00
2.10	0.13	113862	32642060	286.00
1.80	0.00	118257	34475351	291.00
1.50	0.00	105630	2601304819	24626.00
1.20	0.00	66796	2744089420	41081.00
0.90	0.00	26431	2861114214	108248.00
0.60	0.00	3737	2848386288	762212.00
0.30	0.00	48	738594470	15387384.00
```

The columns are 1) p-score (log10(-p)) cutoff, 2) q-score (log10(-q)) cutoff, 3) number of peaks called, 4) total length in basepairs of peaks called, 5) average length of peak in basepair.

This report will assist you how to decide an appropriate cutoff. Because when you gradually lower the cutoff (no matter p or q value), peak caller will pick up weaker binding sites until it suddenly starts to pick more in terms of the jump of 1-order derivative. You can see the behavior between p-score 3.60 (p=0.0002) and 3.30 (p=0.0005).  Now peak caller just starts to pick more noises from the background. I would say that the best cutoff should be selected at p-score 3.6 or q-score 0.83 in this case. Then after certain cutoff, peak caller just starts to merge nearby peaks since ultimately the whole genome should be called as 'peak'. And you will see the behavior after p-score 1.5 (p=0.03), where the average peak length dramatically increases.  

Hope it helps!

Regards,
Tao

**Comment by Bann13** [comment]
Hi, sorry for hijacking this thread, but I couldn't find details of --cutoff-analysis anywhere.

I'm curious about the behaviour in adjusting p and q value as well and this function would be a time saver. However I received this error:

_INFO  @ Mon, 24 Oct 2016 11:47:39: #1.2 read input tags... 
Traceback (most recent call last):
  File "/hpf/tools/centos6/python/2.7.11/bin/macs2", line 617, in <module>
    main()
  File "/hpf/tools/centos6/python/2.7.11/bin/macs2", line 57, in main
    run( args )
  File "/hpf/tools/centos6/python/2.7.11/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 73, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/hpf/tools/centos6/python/2.7.11/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 411, in load_tag_files_options
    control = options.parser(options.cfile[0], buffer_size=options.buffer_size).build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 58, in MACS2.IO.Parser.guess_parser (MACS2/IO/Parser.c:2786)
  File "MACS2/IO/Parser.pyx", line 81, in MACS2.IO.Parser.guess_parser (MACS2/IO/Parser.c:2413)
  File "MACS2/IO/Parser.pyx", line 774, in MACS2.IO.Parser.BAMParser.__init__ (MACS2/IO/Parser.c:11146)
  File "/hpf/tools/centos6/python/2.7.11/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/hpf/tools/centos6/python/2.7.11/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'utoff-analysis'_

command:
macs2 callpeak -cutoff-analysis -f BAM -t sample.bam -n test_p -g hs

version: 2.1.1.20160309

**Comment by dawe** [comment]
@taoliu crystal clear, thanks!
@Bann13 please note that "--cutoff-analysis" option has a double dash, you wrote with a single dash and "-cutoff-analysis" is interpreted as "-c utoff-analysis" (i.e. macs is looking for a control file names "utoff-analysis")

**Comment by Bann13** [comment]
@dawe: good catch ... that was the error. Just curious what did you end up choosing for your cut off? Perhaps due to my limited data size, but I don't really see a dramatic change in npeak (nor lpeak for that matter) like in tao's data where at p-value 3.30 it went from 11982 -> 67161 ( ~5 fold increase).

**Comment by dawe** [comment]
@Bann13 in the end I went for a 0.01 p-cutoff. I should mention the fact I was testing a different approach to call broad domains (which works). @taoliu expect me to write you with a proposal for a modification of the "broad" option :-)

**Comment by taoliu** [comment]
@dawe Hah, yes, please send me your proposal! I am planning to write a MACS2 paper and submit to biorxiv or f1000research (like what you did for your interesting chromatin music paper).

**Comment by taoliu** [comment]
@Bann13 Would you mind to share us the cutoff analysis report?

**Comment by Bann13** [comment]
Hi, @taoliu I have parked this analysis on the side - just got a chance to look at the data again. I am actually working with broadpeaks, so I ended up counting number of peaks from different settings (similar to the narrowPeak cutoff analysis). Actually I do have a question, there will be two "kinks"  in the data if you plot it out (where the second kink is more dramatic). From your experience would it be appropriate to pick the second one? Thanks again.

![image](https://cloud.githubusercontent.com/assets/14165391/21327695/5fbff570-c5fe-11e6-9336-f7deccf8807e.png)

**Comment by taoliu** [comment]
@Bann13 Sorry for very late reply! The two plateaus are obvious in your plot. I would pick a number between 0.3 to 0.45. The first part of increasing number of peaks (q from 0 to 0.15) seems to be due to 'sharp peak', then the second step of increasing (q from 0.2 to 0.3 or # from 100K to 150K) is due to the inclusion of 'broader regions'. Although I can't guarantee that's the correct explanation.

**Comment by Bann13** [comment]
@taoliu That sounds reasonable. Thanks for your comments!
