### ISSUE TITLE
MACS Differential Binding Output And Peak Call Numbers Doesn't Match

### ISSUE THREAD

**Issue by gk7279** [taoliu/MACS#190]
Hi taoliu,

I ran MACS2 callpeak like this

<code>macs2 callpeak -B -t chip11.bed chip21.bed chip31.bed -c input1.bed -n set1 --nomodel --extsize 195 -f BED -g mm</code>

<code>macs2 callpeak -B -t chip12.bed chip22.bed chip32.bed -c input2.bed -n set2 --nomodel --extsize 195 -f BED -g mm</code>

and did bdgdiff to get the differential peaks.

However, the three sets of files that bdgdiff generated had the following numbers

enriched_in_condition1=1428
enriched_in_condition2=29
common=1155

But the MACS2 callpeak command outputs 5349 peaks in the excel sheet for condition1 and 2610 peaks for condition2. This number doesn't match to the numbers from bdgdiff output. Why is it so? Can you please share any pointers. Thanks in advance.

**Comment by taoliu** [comment]
@gk7279 Because the differential caller uses a different type of threshold and parameters (the likelihood ratios) to call the regions. I would suggest you run callpeak for each condition and do an overlap.

**Comment by gk7279** [comment]
Thanks @taoliu . However, each condition has 3 replicates and its own input. But if we run them separately by asking for three bdgs, how do you recommend running bdgdiff to compare more than 1 bdg file? Is that possible? Kindly advice.

**Comment by taoliu** [comment]
Currently, the bdgdiff can ONLY consider 1 to 1 comparison. When I said 'for each condition', it means your pooled condition1 (set1) and condition2 (set2).

**Comment by gk7279** [comment]
Sorry. But I am missing something. I quite didn't get you. What about the overlap? Please share some pointers. Thanks.

**Comment by taoliu** [comment]
@gk7279 About the overlap. What I suggested is to overlap your 5349 cond1 peaks or/and 2610 cond1 peaks with the bdgdiff calls to make a detail comparison. For example, if a peak in the 1428 enriched_in_condition1 list can be found in 5349 cond1 peaks, not in 2610 cond1, then it may be a gain-of-function in condition 1; if a peak in the 1428 enriched_in_condition1 list can be found in both 5349 cond1 peaks and in 2610 cond1, then it may be an increase of enrichment in condition 1. And etc.

**Comment by gk7279** [comment]
Thanks @taoliu . So you are saying to identify the loss of regions during individual calls, I can overlap with the bdgdiff outcomes? And whatever calls are released by bdgdiff are different from the individual calls and are based on likelihood ratios? Any more info? Thanks again!

**Comment by taoliu** [comment]
@gk7279 Don't understand what is the definition of your 'loss of regions'. About your second question, if any called region from bdgdiff does not exist in individual "callpeak" outcomes, that may be caused by cutoff differences -- first the likelihood ratios (LLR) used in bdgdiff vs the Poisson p/q-value used in callpeak; secondly the actual value of the cutoff, e.g. LLR 100 vs 10, or q-value 0.05 vs q-value 0.01 and etc. More information on bdgdiff calls: enriched_in_condition1 calls should be the regions showing stronger (in terms of LLR) cond1 IP enrichment against cond2 IP, and stronger (in terms of LLR) cond1 enrichment against cond1 control; enriched_in_condition2 calls in a similar way; common calls should be the regions showing stronger enrichment comparing cond1 IP to cond1 control, and comparing cond2 IP to cond2 control, and insignificant difference (LLR) between cond1 IP and cond2 IP.

**Comment by gk7279** [comment]
Thank you. This was the explanation I was looking for.
