### ISSUE TITLE
Is the -q parameter supposed to be different from manually filtering by q-value?

### ISSUE THREAD

**Issue by kernco** [taoliu/MACS#253]
I've just found that if I run macs2 peak calling with the parameter "-q 0.01", then I run it again with the exact same input data but with the parameter "-q 0.5" and then filter the called peaks by looking at the second to last column, which is -log10qvalue, and only keeping peaks with a q-value <= 0.01, I get very different numbers of peaks. Filtering manually after running with a higher q-value cutoff results in thousands more peaks. Is this working as intended? What is happening to cause this difference?

**Comment by taoliu** [comment]
You should get different results. The qvalue score reported for the called peaks in output files is the value at the 'summit' point of peak. However, when MACS2 calls peaks, it checks each position in the called region to see if the value is above cutoff. For example, if a region is mostly qvalue=0.1 but the summit (the single basepair) of this region is qvalue=0.01: if you set -q 0.1 and manually filter with q 0.01 then you will get this region; if you set -q 0.01 then MACS2 won't report this region since only 1bp above the cutoff doesn't satisfy.
