### ISSUE TITLE
Q: Pip is confused between 2.1.2 and 2.1.2.1

### ISSUE THREAD

**Issue by tseemann** [taoliu/MACS#295]
Even after a succesful pip upgrade to 2.1.2.1 it still reports the old versio
I think this is a version in the pypi metadata YAML problem perhaps?
Not sure

```
Package Version Latest  Type
------- ------- ------- -----
MACS2   2.1.2   2.1.2.1 sdist
```

**Comment by taoliu** [comment]
They should be the same. The name "2.1.2.1" is for the source code package file, and the actual version is still 2.1.2.

**Comment by tillea** [comment]
Could you please tag 2.1.2.1 in Github anyway.  Its confusing to see a newer version on pypi which is not matching the version number on Github.  Thank you.

**Comment by taoliu** [comment]
Hi @tillea, there is no 2.1.2.1 release version on pypi. The confusion is caused by me, when I uploaded a wrong file to PyPI for MACS2 release 2.1.2, and when I uploaded the correct one the system requires a different name for upload so that's  why the file name becomes MACS2-2.1.2.1.tar.gz. I just created a tag 2.1.2.1 in github and basically it's the same as the tag for 2.1.2. 

https://github.com/taoliu/MACS/releases/tag/v2.1.2.1

**Comment by tseemann** [comment]
I guess we are stuck with this problem forever then:

```
% pip2 list --outdated

Package Version Latest  Type
------- ------- ------- -----
MACS2   2.1.2   2.1.2.1 sdist
```

**Comment by taoliu** [comment]
@tseemann This is a good suggestion. I will release a new 2.1.3 this week.

**Comment by taoliu** [comment]
@tseemann 
@tillea 

A new version 2.1.3.2 has been uploaded to PyPI which has correct tag 2.1.3.2 at github.

https://github.com/taoliu/MACS/releases/tag/v2.1.3.2

https://pypi.org/project/MACS2/2.1.3.2/

BTW, since this is the first time I use Travis to deploy MACS2 to pypi, it made couple of mistakes so that's why the version number becomes 2.1.3.2 instead of 2.1.3...

**Comment by tseemann** [comment]
Thanks @taoliu 

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

**Comment by taoliu** [comment]
@tseemann
Currently, MACS2 setup.py script requires Cython in your system as a dependency.  I will fix this requirement this week. In fact, Cython is not needed during pip installation since all C files are already included.

**Comment by tseemann** [comment]
But if it did need Cython, you need to specify it in `requirements.txt` anyway?

I look forward to the next release.
