### ISSUE TITLE
Q: how can I estimate other species effective genome size？

### ISSUE THREAD

**Issue by axin527** [taoliu/MACS#299]
These days I want to analysis plant ATAC-seq data, and use MACS2 to call peaks. But I don't know how can I estimate a plant effective genome size.

I searched online and saw this page: https://deeptools.readthedocs.io/en/latest/content/feature/effectiveGenomeSize.html. It said that we can use unique-kmers.py to estimate effective genome size. So I used "unique-kmers.py -k ksize TAIR10.fa" with k value 65, 75, 85 and 95. And the biggest result was only 22% of TAIR10 genome length. But the usage of MACS2 said "Because of the repetitive features on the chromsomes, the actual mappable genome size will be smaller than the original size, about 90% or 70% of the genome size. " I think my value is wrong, but I don't know why.

Another way I tried was mask simple repeats, and count the number of capital letters other than N, and it is about 78% of TAIR10 genome length.

**How can I get the right effective genome size for plant? And whether MACS is suitable for plants ATAC-seq data analysis**

Thank you.

**Comment by taoliu** [comment]
Effective genome size basically is the size of the genome that can be potentially covered in the alignment file that you provide to MACS.  So that's why people can use kmer tool to simulate a mapping process, then to estimate the proportion of genome "mappable". Not sure "unique-kmers.py" is the best way to do so since it only allows "uniquely mapped" region. However, most aligner, such as bwa, can report alignment result even if the read can be mapped to multiple regions -- it just randomly pick one unless the read can be mapped to TOO MANY (> certain big number) locations. I don't know what is the best tool to estimate the value. But after removing N and HIGHLY repetitive regions such as simple repeats, the number should be close. So I would just use 78% of genome length as you computed.

**Comment by axin527** [comment]
Do you mean that I can also count the coverage of MACS input file, and then multiply the length of the genome? 

And there is another question. I saw your replies to the ATAC-seq settings and made a summary.
1. To find enriched cutting sites (the 'peak' is where Tn5 transposase likes to attack):
macs2 callpeak -t <BAM> -f BAM --nomodel --shift -100 --extsize 200 -n NAME  -g effective_genome_size
macs2 callpeak -t <BAM> -f BAM --nomodel --shift -75 --extsize 150 -n NAME -g effective_genome_size
2. For PE ATAC-seq reads and let MACS2 pileup the whole fragments in general:
macs2 callpeak -t <BAM> -f BAMPE -n NAME -g effective_genome_size

Is this understanding correct? And is there any other place to pay attention?

Thank you very much!

**Comment by taoliu** [comment]
@axin527 

You should NOT rely on one alignment file (e.g. input file to MACS) to estimate effective genome size. I would simply take 78% of the total genome size as "effective" in your case, based on your calculation.

Yes.

**Comment by axin527** [comment]
好的，大佬，谢谢您！
