### ISSUE TITLE
'Keep duplicates' always ignores duplicates if tagged accordingly in SAM/BAM files

### ISSUE THREAD

**Issue by Gurado** [taoliu/MACS#33]
From the name of the parameter, it appears that "--keep-dup all" should use all duplicate reads regardless of. However, when a sam/bam file contains reads that are properly tagged as PCR or optical duplicate then these reads are ignored in the IO stage. 

[cParser.pyx](../blob/master/MACS2/IO/cParser.pyx) contains the following line of code (twice, lines 566 & 594 in current master)
```if bwflag & 4 or bwflag & 512 or bwflag & 1024:```
which filters reads with corresponding flags (i.e. 1024 for duplicates), therefore ignoring the user's request.

This bug(?) seems to be valid for both macs2 and macs14

**Comment by vschulz** [comment]
I agree with Guraldo.  There is little downside to changing 
if bwflag & 4 or bwflag & 512 or bwflag & 1024:
to 
if bwflag & 4 or bwflag & 512:
since macs will deal with the duplicates as desired by the command given.  Giving a warning that macs will do this is not entirely helpful.  The only theoretical downside would be for people that have marked duplicates so that they would be removed by macs and then don't want to use --keep-dup=1, but they at least have any easy option.  If reads are marked with dups and a user wants to keep them per macs usual procedure, the user has more troublesome options of removing the dup marking, not marking in the first place, or changing the macs code to have a private version as above.

**Comment by taoliu** [comment]
Thanks for your feedback! Will consider it in the next release.

**Comment by taoliu** [comment]
Addressed in 9c988d2.
