### ISSUE TITLE
Q: confuse about the description to --SPMR

### ISSUE THREAD

**Issue by Shicheng-Guo** [taoliu/MACS#357]
Dear Dr. Liu, 

Here, I am a little confuse about --SPMR: 

"If you plan to use the signal output in bedGraph to call peaks using bdgcmp and bdgpeakcall, you shouldn't use this option because you will end up with different results"

What I am thinking is SPMR normalization only change the absolute value and keep the relative values for the pattern, I think there should be no difference with suitable statistic approach, right? hope to receive some help to understand it. 

Thanks. 

Shicheng

**Comment by taoliu** [comment]
@Shicheng-Guo It's the same situation as in the differential gene expression analysis -- some algorithms use FPKM or TPM to compare conditions and some algorithms use counts directly then statistically estimate size-factors to normalize counts. Since MACS2 uses the Poisson test, we expect the values to be compared are discrete "counts".

**Comment by Shicheng-Guo** [comment]
Clear. Thanks.
