### ISSUE TITLE
Bug:  ModuleNotFoundError: No module named 'MACS2'

### ISSUE THREAD

**Issue by yurasong** [taoliu/MACS#387]
**Describe the bug**

When I run the MACS2 on my environment, it returns the error as below,

Traceback (most recent call last):
  File "/usr/bin/macs2", line 31, in <module>
    from MACS2.Constants import *
ModuleNotFoundError: No module named 'MACS2'

Actually I have used it without any problem before installing python3 and change it into the default version. I also tried running macs2 after changing the python version 2.7 but it returns same error.

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version 3.6.9
 - Numpy version numpy-1.18.3
 - MACS Version 2-2.1.0.20151222

**Comment by taoliu** [comment]
@yurasong  This `/usr/bin/macs2` one must come from the one within Ubuntu Linux distribution. You have to modify the `PATH` and `PYTHONPATH` environment to run your own installed version. However, I suggest you follow this [instruction](https://github.com/taoliu/MACS/blob/master/INSTALL.md) to set up either `virtualenv` or `conda` so that you can fully control a software environment which is isolated from the other system-wise software.

**Comment by yurasong** [comment]
@taoliu  Thanks a lot! I tried it and it worked perfectly :)

**Comment by taoliu** [comment]
You are welcome!
