### ISSUE TITLE
Not able to capture large peak

### ISSUE THREAD

**Issue by helenhuangmath** [taoliu/MACS#397]
Hi Dr. Liu and MACS team,

I recently run MACS2 on a *bam file and noticed some issues on my data. 

Firstly, it's a little noisy of my data, I'm not able to capture many peaks (only ~100 peaks) if I use IgG as controls. My first question is that is it possible to take scale factor or downsample for IgG in MACS2? Or do I need to downsampling before run MACS2 for peak calling? 

So I then tried to run macs2 without IgG controls, it woks fine to capture the peaks. 
However, somehow an obvious enriched peak which we thought to be important was not captured, as highlighted in red in attached screenshot (in a large scale and small scale). That peak possibly is wider (~2000bp) than others (~300bp). I've tried broad peak setting using --broad flag and tried different cutoffs from FDR=0.1 to FDR=0.01, but none of them are able to capture that large peak.  

I'm wondering what could be the possible reasons for it? Why does MACS2 capture the small peaks near it, but not that large peak? Is there any parameters that I could tune to capture the peak? 

I appreciate your suggestions!

Thank you,
Helen

<img width="1636" alt="Screen Shot 2020-05-27 at 5 27 47 PM" src="https://user-images.githubusercontent.com/43098514/83089184-b0677c80-a063-11ea-9ab0-60c1daca2c2c.png">
<img width="1635" alt="Screen Shot 2020-05-27 at 9 36 37 PM" src="https://user-images.githubusercontent.com/43098514/83089187-b2314000-a063-11ea-89d6-91faf6aaff83.png">

**Comment by taoliu** [comment]
@helenhuangmath 
Regarding down-sampling, if you have significantly un-balanced case vs IgG data, you can do the down-sampling before peak calling. If the library size of IgG data is bigger,  this step is totally optional since MACS2 will scale-down the bigger IgG data but still try to capture the background noises. 

Regarding the peak calling without IgG, since the background noise will be estimated from case data directly from surrounding genomic regions, I suggest you set `--nolambda` option to skip this behavior and let MACS2 only use the genome background to calculate p-value. I think this will solve this issue.

**Comment by helenhuangmath** [comment]
Thank you Dr. Liu!

**Comment by taoliu** [comment]
@helenhuangmath You are welcome!
